instruction.pdf: slides_source/instruction.tex
	cd slides_source; pdflatex --shell-escape instruction.tex
	cd slides_source; pdflatex --shell-escape instruction.tex
	cd slides_source; pdflatex --shell-escape instruction.tex
	mv slides_source/instruction.pdf .
